FROM --platform=linux/amd64 node:20-buster

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN apt-get update && apt-get install -y wget \
    fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
    libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 \
    libxrandr2 xdg-utils libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 libxss1 chromium



WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies, including dev dependencies for development
RUN npm install

# Bundle app source inside Docker image
COPY . .

# Expose port 3000 for the application
EXPOSE 3000

# Start the application using ts-node for TypeScript execution
CMD ["npx", "nodemon", "--exec", "ts-node", "src/server.ts"]
